### ISSUE TITLE
helloobjectivec doesn't run on all supposedly supported Android versions

### ISSUE THREAD

**Issue by mehlkelm** [gnustep/android-examples#1]
According to the README and the gradle file, GNUstep or the helloobjectivec sample app should support minSdkVersion = 21. I tried to build and run the sample app as is on multiple real and virtual android devices (with Android Studio on macOS 10.15) and managed to run it with Android API level 24 or above. On 21 and 22 the app crashes with 

> java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libgnustep-base.so" needed by "libnative-lib.so"; caused by cannot locate symbol "utext_setup_67" referenced by "libgnustep-base.so"...

**Comment by triplef** [comment]
Thanks for your note and sorry for the delay. We ended up targeting API level 27 (Android 8.1) for our app, that’s why I never ran into this. It sounds like one of the recent library additions to the toolchain must have broken this.

I just gave this a try in the emulator running API level 21 and 22 I am getting a slightly different linker error:

> java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_67" referenced by "libgnustep-base.so"...

API levels 23 and 24 work fine for me.

I think it might be related to [various changes](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#changes-to-library-search-order) to library dependency resolution in Android 23. I am not sure how to fix this though...

Is support for API levels 21 and 22 something you require? Otherwise I’d probably just change the minimum to 23.

**Comment by mehlkelm** [comment]
I don't really "require" level 21, it's just that no other dependency I use has a larger min API level than that, so it would have been convenient to go with that. Let me check what raising the minimum to 23 would mean before I close the issue.

**Comment by triplef** [comment]
I’ve updated the minimum API level to 23.
